# Dependencies
markdown: kramdown
redcarpet:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
excerpt_separator: <!--more-->

# Permalinks
permalink: /blog/:title
timezone: Asia/Beijing
 
# Setup
title: Dongxuan Li (李東轩)
description: 'A Master Student from School of Automation, Beijing Institute of Technology.'
baseurl:     ''
url:         'http://lidongxuan.github.io'

author:
  name: 'Dongxuan Li'
  url: https://github.com/lidongxuan
  email: lidongxuan92@163.com

sass:
  sass_dir: _scss
  compressed: true

paginate: 5

# Custom vars
show_related_posts: false
animated: true

# disqus
# show_disqus_comments: false
disqus_shortname: lidongxuan

# Social icons
show_social_icons: true
github_username: lidongxuan
weibo_username: lidongxuan92

google_analytics: UA-62083650-1


